//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReUzze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.persons = new HashSet<person>();
        }
    
        public int address_id { get; set; }
        public string address_street { get; set; }
        public string address_city { get; set; }
        public Nullable<decimal> address_lat { get; set; }
        public Nullable<decimal> address_lon { get; set; }
        public int address_streetnr { get; set; }
        public int region_id { get; set; }
    
        public virtual region region { get; set; }
        public virtual ICollection<person> persons { get; set; }
    }
}
