//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReUzze.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reuzzeCS2 : DbContext
    {
        public reuzzeCS2()
            : base("name=reuzzeCS2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<bid> bids { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<entity> entities { get; set; }
        public DbSet<favorite> favorites { get; set; }
        public DbSet<medium> media { get; set; }
        public DbSet<person> persons { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<user> users { get; set; }
    }
}
