//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReUzze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.users = new HashSet<user>();
        }
    
        public int person_id { get; set; }
        public string person_firstname { get; set; }
        public string person_surname { get; set; }
        public System.DateTime person_created { get; set; }
        public Nullable<System.DateTime> person_modified { get; set; }
        public Nullable<System.DateTime> person_deleted { get; set; }
        public int address_id { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
