//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReUzze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public region()
        {
            this.addresses = new HashSet<address>();
            this.entities = new HashSet<entity>();
        }
    
        public int region_id { get; set; }
        public string region_name { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<entity> entities { get; set; }
    }
}
